version: '3.7'

services:
  ollama:
    image: ollama/ollama:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ollama_data:/root/.ollama  # Persist model data
      - ./entrypoint.sh:/entrypoint.sh  # Mount custom entrypoint script
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    ports:
      - "11434:11434"
    restart: unless-stopped
    entrypoint: ["/bin/bash", "./entrypoint.sh"]  # Use custom script

  fastapi:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - ollama
    restart: unless-stopped

volumes:
  ollama_data:

networks:
  app-network:
    driver: bridge
